services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=esoft
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
  backend:
    build: backend/
    environment:
      - POSTGRESQL_DSN=postgresql://admin:admin@postgres/esoft
    depends_on:
      - postgres
    ports:
      - 3000:3000
  frontend:
    build: frontend/
    depends_on:
      - backend
    ports:
      - 80:3000